exports.seed = async (knex) => {
  // Inserts seed entries
  await knex('tracks').insert([
    {
      id: 1,
      filepath: 'tracks/Sample1',
      title: 'jam1',
      artist: 'DJ wildcard',
      album: 'Watch yo back',
      notes: 'The best album in the world',
    },
    {
      id: 2,
      filepath: 'tracks/Sample3',
      title: 'Jeds is my Jam',
      artist: 'DJJP',
      album: 'JedsJams',
      notes: "it's hype",
    },
    {
      id: 3,
      filepath: 'tracks/Sample6',
      title: 'jam33',
      artist: 'DJ Nani',
      album: 'Queen Nani',
      notes: "it's lit",
    },
    {
      id: 4,
      filepath: 'tracks/Sample5',
      title: 'jam4',
      artist: 'DJ JennyCraig',
      album: 'watching you',
      notes: "it's sick",
    },
    {
      id: 5,
      filepath: 'tracks/Sample4',
      title: 'based',
      artist: 'DJ DBQueen',
      album: 'Vibes first',
      notes: "it's fun",
    },
    {
      id: 6,
      filepath: 'tracks/Sample4',
      title: 'redux doesnt resux',
      artist: 'DJ Redux Queen',
      album: 'reduxulous',
      notes: "it's cool",
    },
    {
      id: 7,
      filepath: 'tracks/Sample5',
      title: 'woo hoo',
      artist: 'DJ Catfish',
      album: 'You know it',
      notes: "it's awesome",
    },
    {
      id: 8,
      filepath: 'tracks/Sample3',
      title: 'standard',
      artist: 'DJ JazzHands',
      album: '5 hours of average jazz',
      notes: "it's amazing",
    },
    {
      id: 9,
      filepath: 'tracks/Sample1',
      title: 'handle this',
      artist: 'DJ LoveHandles',
      album: 'Can you handle it',
      notes: "it's lovely",
    },
  ])
}
