exports.seed = async (knex) => {
  // Inserts seed entries
  await knex('tracks').insert([
    {
      id: 1,
      filepath:
        'https://res.cloudinary.com/dwjfqnyxs/video/upload/v1664157078/diwaul89qwnzdaurdigu.mp3',
      title: 'intro jam',
      artist: 'Mafra Silyan live band',
      album: 'practise recording for Mafra Silyan 28/09/2022',
      notes: 'Working up new tracks for the live recording',
    },
    {
      id: 2,
      filepath: 'tracks/Sample3.mp3',
      title: 'fast rap one',
      artist: 'Mafra Silyan live band',
      album: 'practise recording for Mafra Silyan 28/09/2022',
      notes: 'Working up new tracks for the live recording',
    },
    {
      id: 3,
      filepath: 'tracks/Sample3.mp3',
      title: 'BIG synth',
      artist: 'Mafra Silyan live band',
      album: 'practise recording for Mafra Silyan 28/09/2022',
      notes: 'Working up new tracks for the live recording',
    },
    {
      id: 4,
      filepath:
        'https://res.cloudinary.com/dwjfqnyxs/video/upload/v1664160392/u5jyu0opalgao03ailqw.m4a',
      title: 'matt talking on the mic for too long',
      artist: 'Mafra Silyan live band',
      album: 'practise recording for Mafra Silyan 28/09/2022',
      notes: 'Working up new tracks for the live recording',
    },
    {
      id: 5,
      filepath: 'tracks/Sample6.mp3',
      title: 'That new banger',
      artist: 'Mafra Silyan live band',
      album: 'practise recording for Mafra Silyan 28/09/2022',
      notes: 'Working up new tracks for the live recording',
    },
    {
      id: 6,
      filepath:
        'https://res.cloudinary.com/dwjfqnyxs/video/upload/v1664159254/yqaaj6xj8jsoayhxaiqx.m4a',
      title: 'That Chris Dave + Timmy Shakes video ',
      artist: 'Chris Dave',
      album: 'From youtube video',
      notes: 'Those amazing lines Timmy Shakes plays',
    },
    {
      id: 7,
      filepath: 'tracks/Sample4.mp3',
      title: 'Kurt Rosenwinkel group live video',
      artist: 'Kurt Rosenwinkel group',
      album: 'Live at Jazzfest',
      notes: 'seems to of gone from you tube',
    },
    {
      id: 8,
      filepath: 'tracks/Sample1.mp3',
      title: 'Dirty Projectors performing for the Roots',
      artist: 'Dirty Projectors',
      album: 'Back stage',
      notes:
        'That lost video of them backstrage with the roots doign the hocketing thing',
    },
    {
      id: 9,
      filepath: 'tracks/Sample3.mp3',
      title: 'jukey',
      artist: 'DOXA',
      album: 'Live recordings from Moon',
      notes: 'to listen back to',
    },
    {
      id: 10,
      filepath: 'tracks/Sample3.mp3',
      title: '5/4 beat',
      artist: 'DOXA',
      album: 'Live recordings from Moon',
      notes: 'to listen back to',
    },
    {
      id: 11,
      filepath: 'tracks/Sample3.mp3',
      title: 'synthy 140 jam',
      artist: 'DOXA',
      album: 'Live recordings from Moon',
      notes: 'to listen back to',
    },
    {
      id: 12,
      filepath: 'tracks/Sample3.mp3',
      title: 'Bottles',
      artist: 'DOXA',
      album: 'Demos',
      notes: 'Listen to in the car',
    },
    {
      id: 13,
      filepath: 'tracks/Sample3.mp3',
      title: 'Temp Synth Track',
      artist: 'DOXA',
      album: 'Rough Mixes',
      notes: 'to listen back to on a walk',
    },
    {
      id: 14,
      filepath: 'tracks/Sample3.mp3',
      title: 'Spit at the Altar',
      artist: 'DOXA',
      album: 'EP2',
      notes: 'Master for reference',
    },
    {
      id: 15,
      filepath: 'tracks/Sample3.mp3',
      title: 'You send me',
      artist: 'Ponderosa twins +1',
      album: 'Ponderosa twins',
      notes: 'lost tracks',
    },
    {
      id: 16,
      filepath: 'tracks/Sample3.mp3',
      title: 'Love and Happiness live',
      artist: 'Al Green',
      album: 'Al Green on Soul trai',
      notes: 'The version with that amazing guitarist ',
    },
    {
      id: 17,
      filepath: 'tracks/Sample1.mp3',
      title: 'Lush Organ',
      artist: 'My Samples',
      album: 'Sample Pack 1',
      notes: ' Nice long organ sample ',
    },
    {
      id: 18,
      filepath: 'tracks/Sample3.mp3',
      title: 'Horns and guitar',
      artist: 'My Samples two',
      album: 'Sample pack 3',
      notes: 'Horn and guitar maybe for that fast beat',
    },
    {
      id: 19,
      filepath: 'tracks/Sample4.mp3',
      title: 'Thump Thump',
      artist: 'Synths etc',
      album: 'Sample pack 2',
      notes: 'Nice clean synth sound ',
    },
    {
      id: 20,
      filepath: 'tracks/Sample5.mp3',
      title: 'Guitar',
      artist: 'Samples',
      album: 'Sample pack 4',
      notes: ' Clean guitar recording',
    },
  ])
}
